from __future__ import annotations

from typing import Any, Protocol


class Provider(Protocol):
    provider_name: str

    def get_user(self) -> dict[str, Any]: ...

    def add_magnet(self, magnet: str) -> dict[str, Any]: ...

    def add_torrent_file(self, path: str) -> dict[str, Any]: ...

    def get_torrent_info(self, torrent_id: str) -> dict[str, Any]: ...

    def select_files(self, torrent_id: str, files: str) -> None: ...

    def unrestrict_link(self, link: str) -> dict[str, Any]: ...

    def delete_torrent(self, torrent_id: str) -> None: ...

    def delete_download(self, download_id: str) -> None: ...

