import type { Job, JobFile, JobDetails } from './jobs.types'

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    name: 'Film.Example.2024.1080p.BluRay',
    status: 'completed',
    provider: 'Real-Debrid (perso)',
    destination: 'NAS Maison',
    fileCount: 3,
    size: '12.4 GB',
    created: '29/05/2026 09:54',
  },
  {
    id: '2',
    name: 'Serie.Example.S03E01-S03.Blu.1080p',
    status: 'downloading',
    provider: 'AllDebrid',
    destination: 'NAS Maison',
    fileCount: 10,
    size: '86.2 GB',
    created: '29/05/2026 08:32',
  },
  {
    id: '3',
    name: 'Documentary.Example.4K.HDR.BluRay',
    status: 'completed',
    provider: 'Real-Debrid (perso)',
    destination: 'NAS Maison',
    fileCount: 1,
    size: '56.8 GB',
    created: '28/05/2026 22:01',
  },
  {
    id: '4',
    name: 'Film.DV.Example.2160p.DDP5.1.Atmos',
    status: 'failed',
    provider: 'Real-Debrid (perso)',
    destination: null,
    fileCount: null,
    size: null,
    created: '28/05/2026 19:17',
  },
  {
    id: '5',
    name: 'Serie.Example.S01E01.720p.BluRay',
    status: 'sent',
    provider: 'AllDebrid',
    destination: 'NAS Maison',
    fileCount: 5,
    size: '8.1 GB',
    created: '28/05/2026 17:30',
  },
  {
    id: '6',
    name: 'Film.Another.2023.1080p.WEB-DL',
    status: 'waiting',
    provider: 'Real-Debrid (perso)',
    destination: 'NAS Maison',
    fileCount: null,
    size: null,
    created: '28/05/2026 15:00',
  },
  {
    id: '7',
    name: 'Show.Example.S04E01-S04E10.HDTV',
    status: 'running',
    provider: 'AllDebrid',
    destination: 'NAS Maison',
    fileCount: null,
    size: null,
    created: '28/05/2026 14:22',
  },
  {
    id: '8',
    name: 'Movie.Example.2160p.HDR.WEBRip',
    status: 'completed',
    provider: 'Real-Debrid (perso)',
    destination: 'NAS Maison',
    fileCount: 2,
    size: '74.3 GB',
    created: '28/05/2026 11:15',
  },
  {
    id: '9',
    name: 'Music.Album.Example.2024.FLAC',
    status: 'cancelled',
    provider: 'AllDebrid',
    destination: null,
    fileCount: null,
    size: null,
    created: '27/05/2026 09:00',
  },
  {
    id: '10',
    name: 'Film.Classic.1990.Remastered.1080p',
    status: 'created',
    provider: 'Real-Debrid (perso)',
    destination: 'NAS Maison',
    fileCount: null,
    size: null,
    created: '27/05/2026 08:30',
  },
]

const SERIES_FILES: JobFile[] = [
  { id: 'f1', name: 'Serie.Example.S03E01.Blu.1080p.mkv', size: '8.8 GB', status: 'completed' },
  { id: 'f2', name: 'Serie.Example.S03E02.Blu.1080p.mkv', size: '8.6 GB', status: 'completed' },
  { id: 'f3', name: 'Serie.Example.S03E03.Blu.1080p.mkv', size: '9.1 GB', status: 'downloading' },
  { id: 'f4', name: 'Serie.Example.S03E04.Blu.1080p.mkv', size: '8.9 GB', status: 'waiting' },
]

const FILM_FILES: JobFile[] = [
  { id: 'f1', name: 'Film.Example.2024.1080p.BluRay.mkv', size: '12.2 GB', status: 'completed' },
  { id: 'f2', name: 'Film.Example.2024.1080p.BluRay.nfo', size: '2 KB', status: 'completed' },
  { id: 'f3', name: 'Film.Example.2024.1080p.BluRay.jpg', size: '156 KB', status: 'completed' },
]

export const MOCK_JOB_DETAILS: Record<string, JobDetails> = {
  '1': {
    ...MOCK_JOBS[0],
    jobPath: '/data/jobs/d96abc12',
    files: FILM_FILES,
    progress: { percent: 100, downloadedSize: '12.4 GB', speed: null, eta: null, connections: 0, provider: 'Real-Debrid (perso)' },
  },
  '2': {
    ...MOCK_JOBS[1],
    jobPath: '/data/jobs/a4f731de',
    files: SERIES_FILES,
    progress: { percent: 45, downloadedSize: '38.8 GB', speed: '12.4 MB/s', eta: '1h 23m', connections: 4, provider: 'AllDebrid' },
  },
  '4': {
    ...MOCK_JOBS[3],
    jobPath: '/data/jobs/b2e90fa1',
    files: [],
    progress: { percent: 0, downloadedSize: null, speed: null, eta: null, connections: 0, provider: 'Real-Debrid (perso)' },
  },
}
