export const state = {
  jobs: [],
  currentUser: null,
  selectedJob: null,
  selectedJobId: null,
  jobsStatusFilter: "",
  jobsPollTimer: null,
  systemPollTimer: null,
  currentActionKey: null,
  system: null,
  controlCenter: null,
  restartCooldowns: {
    default_seconds: 10,
    realdebrid_seconds: 60,
    alldebrid_seconds: 8,
  },
  activePage: localStorage.getItem("link2nas_active_page") || "jobs",
  language: localStorage.getItem("link2nas_language") || "fr",
  detailPanelsByJobId: {},
  providers: [],
  destinations: [],
  users: [],
  activeAdminTab: "users",
  notificationConfigs: [],
  userApiKeys: [],
  generalSettings: null,
  appInfo: null,
  announcements: [],
  adminAnnouncements: [],
  announcementTrackingById: {},
  dismissedAnnouncementBannerIds: [],
  integrationSettings: {
    prowlarr_enabled: false,
    prowlarr_url: "",
    prowlarr_open_mode: "both",
    home_page: "jobs",
  },
};
