import { useState, useEffect, useCallback } from 'react'
import { AlertCircle, AlertTriangle, Info, Loader2, RefreshCw, XCircle } from 'lucide-react'
import SectionCard from '@/components/common/SectionCard'
import { Button } from '@/components/ui/button'
import { listNotificationEvents } from '@/api/admin-notifications'
import type { AdminNotificationEvent, NotificationEventStatus, SystemEventSeverity } from './admin.types'
import { isSystemNotificationEvent } from '@/lib/notification-filters'
import { useAppInfo } from '@/lib/useAppInfo'
import { useI18n } from '@/i18n'
import type { TranslationKey } from '@/i18n'

const SEV: Record<SystemEventSeverity, { icon: React.ReactNode; color: string }> = {
  critical: { icon: <XCircle size={13} aria-hidden="true" />,      color: 'text-red-700 dark:text-red-400'   },
  error:    { icon: <AlertCircle size={13} aria-hidden="true" />,  color: 'text-red-600 dark:text-red-400'   },
  warning:  { icon: <AlertTriangle size={13} aria-hidden="true" />,color: 'text-amber-600 dark:text-amber-400'},
  info:     { icon: <Info size={13} aria-hidden="true" />,          color: 'text-blue-600 dark:text-blue-400' },
}

const STATUS_BADGE: Record<NotificationEventStatus, string> = {
  sent:     'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950 dark:text-emerald-400',
  failed:   'border-red-200 bg-red-50 text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-400',
  retrying: 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-400',
  pending:  'border-border bg-muted text-muted-foreground',
  ignored:  'border-border bg-muted text-muted-foreground',
}

const PILL = 'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium'
const LIMITS = [25, 50, 100, 200]

function fmt(iso: string | null | undefined): string {
  return iso ? new Date(iso).toLocaleString() : '—'
}

function EventItem({ ev }: { ev: AdminNotificationEvent }) {
  const { t } = useI18n()
  const sev = SEV[ev.severity] ?? SEV.info
  return (
    <li className="flex items-start gap-3 py-3">
      <span className={`mt-0.5 shrink-0 ${sev.color}`}>{sev.icon}</span>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
          <span className="font-mono text-xs text-foreground">{ev.type}</span>
          <span className={`${PILL} ${STATUS_BADGE[ev.status]}`}>{ev.status}</span>
          {ev.attempts > 1 && (
            <span className="text-xs text-muted-foreground">{ev.attempts}/{ev.max_attempts} {t('adminEvAttempts')}</span>
          )}
        </div>
        <p className="mt-0.5 text-sm font-medium text-foreground">{ev.title}</p>
        {ev.message && ev.message !== ev.title && (
          <p className="mt-0.5 text-xs text-muted-foreground">{ev.message}</p>
        )}
        {ev.last_error && (
          <p className="mt-1 break-words rounded bg-red-50 px-2 py-1 text-xs text-red-700 dark:bg-red-950 dark:text-red-400">
            {ev.last_error}
          </p>
        )}
        <p className="mt-1 text-xs text-muted-foreground">
          {fmt(ev.created_at)}
          {ev.sent_at && ` · sent ${fmt(ev.sent_at)}`}
          {ev.next_retry_at && ` · retry ${fmt(ev.next_retry_at)}`}
        </p>
      </div>
    </li>
  )
}

export default function AdminSystemEvents() {
  const { t } = useI18n()

  const STATUS_CHIPS: { key: NotificationEventStatus | 'all'; labelKey: TranslationKey }[] = [
    { key: 'all',      labelKey: 'adminEvAll'      },
    { key: 'pending',  labelKey: 'adminEvPending'  },
    { key: 'sent',     labelKey: 'adminEvSent'     },
    { key: 'failed',   labelKey: 'adminEvFailed'   },
    { key: 'retrying', labelKey: 'adminEvRetrying' },
    { key: 'ignored',  labelKey: 'adminEvIgnored'  },
  ]

  const [events, setEvents] = useState<AdminNotificationEvent[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [statusFilter, setStatusFilter] = useState<NotificationEventStatus | 'all'>('all')
  const [limit, setLimit] = useState(50)
  const { appInfo } = useAppInfo()
  const appName = appInfo.app_name || 'Link2NAS'

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const all = await listNotificationEvents({
        limit,
        status: statusFilter === 'all' ? undefined : statusFilter,
      })
      setEvents(all.filter(isSystemNotificationEvent))
    } catch (err) {
      setError(err instanceof Error ? err.message : t('adminLoadEventsFailed'))
    } finally {
      setLoading(false)
    }
  }, [statusFilter, limit])

  useEffect(() => { load() }, [load])

  return (
    <SectionCard
      title={t('adminEventsTitle')}
      description={`Notification events generated by ${appName}, including system-level alerts.`}
      actions={
        <Button size="sm" variant="outline" onClick={load} disabled={loading}>
          {loading
            ? <Loader2 size={13} className="mr-1.5 animate-spin" aria-hidden="true" />
            : <RefreshCw size={13} className="mr-1.5" aria-hidden="true" />}
          {t('refresh')}
        </Button>
      }
    >
      {/* Filter bar */}
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="flex flex-wrap gap-1.5">
          {STATUS_CHIPS.map(({ key, labelKey }) => (
            <Button key={key} size="sm"
              variant={statusFilter === key ? 'default' : 'outline'}
              className="h-7 text-xs"
              onClick={() => setStatusFilter(key)}>
              {t(labelKey)}
            </Button>
          ))}
        </div>
        <div className="flex items-center gap-1.5 ml-auto">
          <span className="text-xs text-muted-foreground">{t('adminEventsLimit')}</span>
          <select
            value={limit}
            onChange={(e) => setLimit(Number(e.target.value))}
            className="h-7 rounded-md border border-input bg-background px-2 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          >
            {LIMITS.map((l) => <option key={l} value={l}>{l}</option>)}
          </select>
        </div>
      </div>

      {loading && (
        <div className="flex items-center gap-2 py-8 text-muted-foreground">
          <Loader2 size={18} className="animate-spin" aria-hidden="true" />
          <span className="text-sm">{t('adminLoadingEvents')}</span>
        </div>
      )}

      {error && !loading && (
        <div className="flex items-start gap-3 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-400">
          <AlertCircle size={15} className="mt-0.5 shrink-0" aria-hidden="true" />
          <div>
            <p className="font-medium">{t('adminLoadEventsFailed')}</p>
            <p className="mt-0.5 text-xs">{error}</p>
            <Button size="sm" variant="outline" className="mt-3" onClick={load}>{t('retry')}</Button>
          </div>
        </div>
      )}

      {!loading && !error && events.length === 0 && (
        <p className="py-6 text-sm text-muted-foreground">
          {t('adminNoEvents')}{statusFilter !== 'all' ? ` with status "${statusFilter}"` : ''}.
        </p>
      )}

      {!loading && !error && events.length > 0 && (
        <ul className="divide-y divide-border">
          {events.map((ev) => <EventItem key={ev.id} ev={ev} />)}
        </ul>
      )}
    </SectionCard>
  )
}
